### ISSUE TITLE
spring mobile does not work with Spring Boot 2

### ISSUE THREAD

**Issue by armdev** [spring-projects/spring-mobile-samples#1]
Hello,
I tried to integrate spring mobile with spring boot 2(webflux), but because mobile has dependency from tomcat, application fails.

**Comment by royclarkson** [comment]
Thanks for reporting. Spring Mobile does support Spring Boot 2 MVC applications, however the auto configuration and starters have been removed from Spring Boot and the coordinates have changed. Unfortunately, there are no plans to support WebFlux at this time.
